openapi: 3.0.0
# Added by API Auto Mocking Plugin
servers:
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/jm-root/jm-pay/1.0.0
info:
  version: "1.0.0"
  title: jm-pay-api
  description: 支付API
paths:
  '/pay/pays':
    get:
      description: 查询付款单列表
      parameters:
        - name: page
          in: query
          description: 第几页
          schema:
            type: integer
            format: int32
            minimum: 1
        - name: rows
          in: query
          description: 行数
          schema:
            type: integer
            format: int32
            minimum: 1
      responses:
        '200':
          description: 查询结果
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pays'
    post:
      description: 创建付款单
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Pay'
      responses:
        '200':
          description: 创建成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pay'
  '/pay/pays/{id}':
    get:
      description: 查询指定付款单
      parameters:
        - name: id
          in: path
          description: 付款单id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 查询结果
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pay'
    post:
      description: 更新指定付款单
      parameters:
        - name: id
          in: path
          description: 付款单id
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Pay'
      responses:
        '200':
          description: 查询结果
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pay'
    delete:
      description: 删除指定付款单
      parameters:
        - name: id
          in: path
          description: 付款单id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 结果
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ret'
  '/pay/refunds':
    get:
      description: 查询退款单列表
      parameters:
        - name: page
          in: query
          description: 第几页
          schema:
            type: integer
            format: int32
            minimum: 1
        - name: rows
          in: query
          description: 行数
          schema:
            type: integer
            format: int32
            minimum: 1
      responses:
        '200':
          description: 查询结果
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Refunds'
    post:
      description: 创建退款单
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Refund'
      responses:
        '200':
          description: 创建成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Refund'
  '/pay/refunds/{id}':
    get:
      description: 查询指定退款单
      parameters:
        - name: id
          in: path
          description: 退款单id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 查询结果
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Refund'
    post:
      description: 更新指定退款单
      parameters:
        - name: id
          in: path
          description: 退款单id
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Refund'
      responses:
        '200':
          description: 查询结果
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Refund'
    delete:
      description: 删除指定退款单
      parameters:
        - name: id
          in: path
          description: 退款单id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 结果
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ret'
components:
  schemas:
    Ret:
      type: object
      properties:
        ret:
          type: integer
          format: int32
          description: 1 成功 0 失败
      description: 操作结果
    Pay:
      type: object
      properties:
        code:
          type: string
          description: 付款单编号
        orderId:
          type: string
          description: 关联订单id
        payee:
          type: string
          description: 收款用户id
        payer:
          type: string
          description: 付款用户id
        channel:
          type: string
          description: 支付渠道
        currency:
          type: string
          description: 币种
        amount:
          type: integer
          format: int64
          description: 金额，人民币单位为分
        bill:
          type: object
          description: 第三方支付票据
        memo:
          type: string
          description: 备注信息
        title:
          type: string
          description: 标题
        content:
          type: string
          description: 内容
        status:
          type: integer
          format: int32
          description: 状态 0无效 1未支付 2已支付 3已退款
    Pays:
      type: object
      properties:
        rows:
          type: array
          items:
            $ref: '#/components/schemas/Pay'
        page:
          type: integer
          format: int32
          description: 当前页
        total:
          type: integer
          format: int32
          description: 总行数
        pages:
          type: integer
          format: int32
          description: 总页数
      description: 列表
    Refund:
      type: object
      properties:
        code:
          type: string
          description: 退款单编号
        pay:
          type: string
          description: 对应付款单
        amount:
          type: integer
          format: int64
          description: 金额，人民币单位为分
        bill:
          type: object
          description: 第三方退款票据
        status:
          type: integer
          format: int32
          description: 状态 0未退 1已退款 该状态为逻辑状态,不代表实际退款结果.
    Refunds:
      type: object
      properties:
        rows:
          type: array
          items:
            $ref: '#/components/schemas/Pay'
        page:
          type: integer
          format: int32
          description: 当前页
        total:
          type: integer
          format: int32
          description: 总行数
        pages:
          type: integer
          format: int32
          description: 总页数
      description: 列表